services:
  - type: web
    name: muwandb-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: VITE_API_URL
        sync: false
